### ISSUE TITLE
Why not on App Store?

### ISSUE THREAD

**Issue by goerz** [larki/VimIOS#7]
I'm just wondering why this fork is not on the App Store. The original implementation by @applidium is still there, so I'm assuming there's no licensing issue. Couldn't someone just package up whatever the most advanced fork is and put it on the App Store? I'd rather pay someone $20 to download a working version of this app than $99 to Apple per year to sideload this in any useful way.

I'd especially like to see this kept up to date with any of @holzschu's modifications to make Vim work in conjunctions with @blinksh

**Comment by holzschu** [comment]
He raises a good question. This is a good port of Vim on iOS (better than @applidium's). I think there are people out there interested by it, and who don't want to sideload it. What would it take to make this app available on the App store? I'm ready to help.

**Comment by larki** [comment]
I am glad you enjoy the port! Aside from potential license issues (which I know nothing about), there are several personal reasons why I did not put the port on the App Store (in no particular order):

- I have no time to maintain it.
- I am not a member of the apple developer program.
- My original port was almost a 1-to-1 copy of the @applidium port, which I did because I wanted to learn some iOS/Swift development, and because I was excited about the then new iPad Pro. I did not have the time to polish it enough to put it on the App Store, and in any case, it felt too derivative.

That being said, I have no objections to someone else polishing it more and putting it on the web store, in fact I would love to have a port more fully integrated into iOS. This might make me buy a "Smart Keyboard" again :)

BTW: When I last checked, I did not need to have a $99 subscription to the Apple developer program to side-load the Vim port, as it does not use any of the restricted kits. My free Apple dev account was sufficient.

**Comment by goerz** [comment]
Yeah, I managed to sideload it after deactivating iCloud support. However, it only works for 7 days, as far as I can tell. That's really not a workable solution, unfortunately. Apple is really out of their minds on this nonsense. :-/

**Comment by larki** [comment]
Ah, this 7 days restriction is news to me :/

**Comment by goerz** [comment]
@holzschu If this is released, the App-Group with @blinksh would be pretty important, to share files.  I suppose the next iOS version will expand the possibilities considerably, with Edit in Place and such. At the point where your work to integrate shell utilities was merged into Blink, maybe this could be released as a "Vim for Blink" partner app? Maybe until then this could find a place in TestFlight?

I feel kinda bad pushing you or Carlos towards doing this sort of maintenance work, but then again, I would be more than happy to pay a substantial price tag.

**Comment by carloscabanero** [comment]
I'm an emacs guy and working on closing other things right now, but count me in with anything I can help to make this happen. I took a look at it a while ago and the other issue might be the license within iOS, but nothing we can't get advice for.

**Comment by xslim** [comment]
I have a dev account, and also can release it in TestFlight for "beta" testers, but I don't have much time to maintain this. 
I could however automate the release, say based on a tag to auto-release...

**Comment by holzschu** [comment]
With the "open-in-place" feature (new in iOS 11), we don't need to have Vim as a companion app of @blinksh. Also, with external keyboard support + copy and paste + open-in-place, there are now significant differences with @applidium's port. 

That said, has anyone tried to contact @applidium?

**Comment by mtwebb** [comment]
Count me in with those excited to pair blink + vim natively on iPad pro. Text manipulation via touchscreen is glacially slow.   @holzschu excited to see your shell functionality additions to blink shell.  An os just doesn’t feel like home without vim.  @xslim a test flight verion would be great in the interim.

**Comment by nicolasbraun** [comment]
Hi @larki and folks,

I am part of Applidium's managing team. Like you it's mainly time that prevented us to maintain Vim properly but we definitely wanted to do a proper iOS11 release. It also means looking at forks and PR to release the best version as possible.

@larki would you have any objection if your developments where integrated back into the original repository?

Sadly our CI processes are not integrated with github but at least we will also setup automatic appStore / Tesflight deployment to ease the release process in the future.

**Comment by larki** [comment]
Hi Nicolas, that's great news! I have no objections at all, on the contrary.

**Comment by holzschu** [comment]
Same as @larki : no objections, so long as the result is still open source and I can tinker with it.

**Comment by goerz** [comment]
Another fork ([iVim](https://github.com/terrychou/iVim)) is now on the app store

**Comment by markboston34** [comment]
What’s the status of adding it to the AppStore?
